### ISSUE TITLE
Refactor filters to match new designs

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#597]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need the page filters to shift to the [new design](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1922%3A1416&mode=design&t=wJbQuLA9f6WijJvO-1). Changes include the following:

- [ ] We need to have a background card and element widths need to be shifted to reflect this
- [ ] We should switch the topic selection interface to a version of the topic selection component being finalized in #527 
- [ ] Form group components should be refactored using [Headless UI](https://headlessui.com/) to assure a11y
- [ ] A tooltip to explain event type should be added
- [ ] Colors of all elements should be changed to match the designs
- [ ] Along with the above we can also add in the focus state coloration that wasn't finished in #548 
- [ ] Allowing for deselect of the form radio groups as planned in #551 
- [ ] The arrows for the options in the sidebar footer are sometimes visible when the sidebar is collapsed

### Contribution

I'll be working on this :)
